### ISSUE TITLE
Touhou Character Mods on Github?

### ISSUE THREAD

**Issue by Blizihguh** [GriefSyndromeModderTools/AML2#1]
Hello,

It's only tangentially related to this repository, but this seemed like the best place to ask. Would it be possible to upload your Touhou character mods to Github? (The Remilia, Patchouli, and Komachi ones, as seen [on your group page](https://griefsyndromemoddertools.github.io/).) It seems like the only way to download them right now is through your QQ group, which is difficult to join as someone who doesn't use QQ and can't read Chinese. Any way of downloading them outside of QQ would be appreciated, but Github seems like a good fit since you have lots of other GriefSyndrome modding repositories anyway.

Thank you!

**Comment by acaly** [comment]
Thanks for the interest for the mods! For some reasons I don't want to publish them on GitHub. I have previously created a discord server, for discussion with another player who can't read Chinese. Do you mind join us there?

https://discord.gg/k68zMJtN

**Comment by meowmeowch** [comment]
Hello! can you give a new links discord?
i like your mods!

**Comment by acaly** [comment]
@meowmeowch Welcome! Here's the new link: https://discord.gg/5B3vH2hg

For anybody who read this in the future: it's becoming harder and harder for us to use discord (for reason you know). I may not be able to reply on discord very soon. I think it's probably better to publish the mods on GitHub finally.

**Comment by meowmeowch** [comment]
hello! I might be being rude, but could you please make this a permanent link? It won't take long for me to read it. The link has expired. 
(You don't have to reply. If I'm too rude) Sorry for wasting your time.

**Comment by acaly** [comment]
That's OK. Don't mind. We are really happy to see other people playing our mods.

I remember I generated a permanent invitation. I'm sorry it is not working again. Here's a new link. Please try it. https://discord.gg/Qq4cuNMtfh

(I double checked the option this time. So if you can't join, there must be some problem with GitHub or Discord.)
